# Change the following fields to the desired file name and paths
dataset: cohortA

input:
  final_report: /path/to/cohortA/finalreport.txt
  sample_info: /path/to/cohortA/samplesheet.csv

output_dir: results/cohortA

#############################################################################
########################### DO NOT CHANGE ###################################

chromosomes: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

HRC_script: /groups/umcg-immunogenetics/tmp02/users/NathanRibeiro/tools/HRC_check_tool/HRC-1000G-check-bim-NoReadKey.pl
HRC_reference: /groups/umcg-immunogenetics/tmp02/users/NathanRibeiro/tools/HRC_check_tool/HRC.r1-1.GRCh37.wgs.mac5.sites.tab

python2_path: /groups/umcg-immunogenetics/tmp02/users/NathanRibeiro/tools/python2.7.9/bin/
openssl_path: /groups/umcg-immunogenetics/tmp02/users/NathanRibeiro/tools/openssl1.0.2/lib

checkvcf_ref: /groups/umcg-immunogenetics/tmp02/users/NathanRibeiro/tools/checkVCF/hs37d5.fa

##############################################################################
##############################################################################