executor: slurm
jobs: 50
latency-wait: 60

default-resources:
  - runtime=00:30:00
  - mem=8gb
  - cpus_per_task=1

cluster:
  sbatch
  --job-name=smk-{rule}
  --output=logs/%x.%j.out
  --error=logs/%x.%j.err
  --cpus-per-task={resources.cpus_per_task}
  --mem={resources.mem}
  --time={resources.runtime}
  --nodes=1